// Arquivo de configuração das sidebars do Docusaurus (sidebars de cada área)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  
  // Sidebar de Programação
  programacaoSidebar: [
    {
      type: 'autogenerated',
      dirName: 'programacao', 
    },
  ],

  // Sidebar de Arquitetura
  arquiteturaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'arquitetura',
    },
  ],

  // Sidebar de Eletrônica
  eletronicaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'eletronica',
    },
  ],
};

export default sidebars;